### ISSUE TITLE
provide rating info while exploring sounds in a category

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#110]
Currently, when exploring the sounds/annotations in a category (due to the mapping), the only information provided is the sounds (spectrogram/waveform) and its url to Freesound. Therefore, the user does not know whether the sound has been already validated and with which ratings.

It is informative to **include the type and number of votes**, so that the user is aware. For example by hovering on the spectrogram/waveform, or on the corresponding row of the table.

Example:
_PP:1
PNP:2
U:0
NP:0_

**Comment by xavierfav** [comment]
The type and number of votes for each category table has been added.

The sorting is not trivial, some SQL queries should be done for allowing a complex sorting as proposed here. For now, the sounds are sorted using the number of votes. First the one with more votes.

In the future, we will add the possibility to sort according any vote value.
