### ISSUE TITLE
Exploration of a sound category

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#111]
Currently, when exploring the sounds/annotations in a category (due to the mapping), the sounds  are listed in no particular order. 

The user is exploring the result of the mapping. Due to potential mapping failures, there may be sounds that do not really belong to the category.

Perhaps it makes more sense to show first the sounds/annotations validated with better (_present_) ratings. This will enhance user experience, together with #110 .

Example of sorting (needs refinement, the main idea is PP and PNP first, U and NP last):

**1) sounds validated with PP (with majority agreement, i.e., ground truth (GT))
2) PNP (GT)**

3) PP (not GT yet)
4) PNP (not GT yet)

5) U (not GT yet)
6) NP (not GT yet)

**7) U (GT)
8) NP (GT)**

**Comment by xavierfav** [comment]
The type and number of votes for each category table has been added.

The sorting is not trivial, some SQL queries should be done for allowing a complex sorting as proposed here. For now, the sounds are sorted using the number of votes. First the one with more votes.

**Comment by xavierfav** [comment]
One of our goal is to provide **tools for the exploration of the dataset realeses and its current state**.
Some basic things we may want:

- **Sort** candidate sounds by vote types counts
- See the **ground truth states** (including presence or non presence)
- Replace the freesound link by a smaller freesound icon (similar to the one used in the validation task)


**Another nice thing** to complemente the _category-based view_ would be to prived a _sample-based view_, where the candidates of a sound are displayed.
It should not be so much work to use some tools created for the generation task #134.
We could show the path of each candidate and display their number of votes.
This could be a start for slowly and wisely intrucing other type of tasks, by introducing a tool for refining annotations (same as generation task, but without the _exploration_ stage, check the [deliverable document](https://www.audiocommons.org/assets/files/AC-WP5-UPF-D5.4%20Research%2C%20development%20and%20evaluation%20of%20an%20interface%20for%20manually%20annotating%20non-musical%20content.pdf).

**Comment by xavierfav** [comment]
This should be discussed in #33.
