### ISSUE TITLE
Add cookie banner

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#128]
For now we use cookie just for user session, it might to be mandatory to ask user to accept our use of cookie (not sure).

However, if we add tools like google analytics, it would need to add it.

[Here](https://github.com/dobarkod/cookie-banner) is a code for the cookie banner.

**Comment by lorenzo-romanelli** [comment]
In commit https://github.com/MTG/freesound-datasets/commit/ab4e8efca44688265225f028203cc20eb4bb74ec I added the basic code to display the cookie banner.

We still need to create a page where the cookie policy is described, and link to it in the `data-moreinfo` attribute here (`freesound-datasets/templates/base.html`, lines 26-30)
```html
<script type="text/javascript"
        id="cookiebanner"
        src="https://cdnjs.cloudflare.com/ajax/libs/cookie-banner/1.2.2/cookiebanner.min.js"
        data-moreinfo="#">
</script>
```
