### ISSUE TITLE
Add new Freesound sounds & candidates to FSD

### ISSUE THREAD

**Issue by jordipons** [MTG/freesound-datasets#130]
Currently, not all Freesound sounds are available in FSD.

It would be handy if every time we add a new Freesound sound id in FSD, it would be automatically added to the FSD database so that it is accessible for the platform.

**Comment by xavierfav** [comment]
I don't think adding Freesound sounds by hand is the right way of doing.
It would mean you'll have to add thousands sounds per week manually...

Also, we'll need to assign some candidate annotations to the added sounds.

I think we should have a command for synchronizing to Freesound:
- Retrieve new Freesound sounds (which follow our criteria, ie < 90 sec)
- Run the mapping for creating the candidate annotations
- Create the instances and store them in the database

**Comment by xavierfav** [comment]
Some categories have not much more candidates.
Moreover, the tag based mapping rule is sometimes bad and needs to be improved.

I propose to provide a tool to **add candidates directly from the platform**.

For a single category, a page would provide a basic interface for doing some SOLR syntax tag based queries, e.g.:
`bark AND NOT dog AND NOT dogs` would correspond to this query:

- URL: `http://freesound.org/apiv2/search/text/?&query=&filter=tag:(bark%20AND%20NOT%20dog%20AND%20NOT%20dogs)`
- Freesound python client: `c.text_search(query='', filter='tag:(bark AND NOT dog AND NOT dogs)')`

The interface would display a few random sounds from the query to be able to quickly evaluate the quality of the retrieved candidates. 
If the quality is acceptable, it could be possible to automatically add all the candidates to FSD.


One drawback of doing it like that is that it is not performing the [stemming pre-processing step](https://en.wikipedia.org/wiki/Stemming) that we first used for generating the candidates the first time. This would imply to manually add the tags `dog AND dogs ` for instance.

However, it would give the possibility to experiment a bit with some mapping rules, and give the opportunity to any maintainer to add new candidates to FSD.

**Comment by edufonseca** [comment]
I think this is great. It's an agile way to experiment with a few different accept/reject tags to perform a mapping from Freesound. It'd be great to be able to specify a DATE filter in the query too. The 20-30 sounds retrieved would be instrumental to evaluate the mapping before eventual acceptance.

Two modes could be useful:

1. **Add**. From a given date on, retrieve data, additionally to what there is in database. Useful for classes with no candidates left.

2. **Replace**. For all times, retrieve data. After inspection of the data retrieved, it'd be great to be able to choose **replace** existing data. This means:
    - delete from database those ids that are ***not*** suggested now (assuming they are incorrect samples)
    -  only when they have not been voted yet (or they have been voted with NP/U maybe?)

The latter is useful for improving the state of classes with a lot of wrongly mapped data in the platform, like Hiss or Growling.

**Comment by jordipons** [comment]
I also think that it is a great idea, and I propose to design this having in mind that alternative sources of candidates can be available. For example, a source of novel candidates can be any content-based model.

At the end of the day these SOLR syntax tag-based queries will provide a list of IDs, right? It would be nice if the new tool also accepts a list of Freesound IDs -- that could be computed offline by any other model/approach.

Besides that, how do you see this "quality evaluation"? What if we do 1 or 2 (or few) pages of the current annotation interface with these novel candidates? And the votes we do directly contribute to the system?

**Comment by xavierfav** [comment]
Thanks for the feedback!

- Date filtering is planned
- Add/replace option
- **Entering Freesound id manually** is also planned and it is kind of the solutuon for the original issue opened by @jordipons 
- For allowing external/offline and more complicated mapping, I was thinking of allowing to **upload a CSV with the Freesound ids** for instance.
- The stemming process could still be done here. There would be several way to do it. For instance, an offline preprocessing of all the tags in Freesound could provide the un-stemmed tags of all the stemmed forms, and then we could expand our queries automatically. Or maybe, the way to go is to stop relying on the Freesound API to do these queries, and use our database...
- For the idea of saving the "quality evaluation" votes, we'll see how the implementation goes, it might not be so straightforward to implement this feature. And if it is just for saving around 20 votes, it is maybe not so worth.

**Comment by jordipons** [comment]
Sounds good! 

If the "quality evaluation" feature is hard to implement, I would recommend not to do it. However, let's think a little bit more to see if we can find an easy way to do that -- because this feature could be very interesting, I think. But let's try to keep things simple!

**Comment by xavierfav** [comment]
**A first category mapping tool has been deployed!**
You can access the category mapping page from a monitor category page
![image](https://user-images.githubusercontent.com/10927428/43319619-aba4827a-91a5-11e8-8f5f-fcc1d7bfb1bb.png)

All of the features mentioned previously have not been added yet, but I think the tool can already be used and we can see how to improve it in the future (TODO: date filtering, csv upload).

**The interface has different blocks:**

- First it **lists the mapping rule rules** originally used, and also the one used directly in the platform.
![image](https://user-images.githubusercontent.com/10927428/43319721-0b86be4c-91a6-11e8-95c1-81a199404103.png)

   - ['acapella'] (or [['acapella']]) means that we accepts sounds that have acapella tag (remember we used stemming originally)
  - [['acapella', 'voice']] would mean that we accepts sounds that have both acapella and voice tags. 

- You can **add candidates by Freesound ID**. Note that this will not work with sounds that are not in our platform. We will have to add the new Freesound sounds soon.
![image](https://user-images.githubusercontent.com/10927428/43319882-a5458040-91a6-11e8-9f06-314ab42101d6.png)

- You can try **new tag-based retrieval rules**
![image](https://user-images.githubusercontent.com/10927428/43319986-208b5b1c-91a7-11e8-8975-86dfd3f946cc.png)
Each line of the _Include tags_ part correspond to different accepted tag matching rules that are combined.
Comma separated terms in one line correspond to a AND rule of tag matching.
With the _Omit tags_ part, we can exclude sounds that have one of the comma separated term as tag.
Here the query could be translated to:
`(acapella AND voice) OR (acapella AND sing) AND NOT (guitar OR bass)`
Note that you can enable or disable [stemming](http://www.nltk.org/howto/stem.html).

- After submitting you query, **wait that the system outputs you some informations**
![image](https://user-images.githubusercontent.com/10927428/43320598-46d28014-91a9-11e8-87e2-81d665e66b1d.png)
    - At the right you have statistics about the actual candidates we have in the platform. On the left about the retrieval method you just submitted. The quality estimate automatically generated is to be used carefully. You should not trust it blindly, and should check how many sounds were retrieved, how many votes were used for the evaluation.
    - The tags of the sounds that were voted Not Present are shown together with their number of occurrences. This can help helpful when you want to refine you query by adding some _Omit tags_
    - You can listen to sounds and validate them. This will give you another quality estimate which is more reliable.

- Once you found the new state of the art tag query, you can **submit the new candidates**
![image](https://user-images.githubusercontent.com/10927428/43320711-a906a800-91a9-11e8-9086-2d9d0b4633f7.png)
There are two options:
    - You can add the new sounds as candidate without touching the existing ones.
    - You can replace the candidates. This will remove the existing one (that were never voted), and add the new ones.

- The interface ask you **if you are sure** you want to proceed.
![image](https://user-images.githubusercontent.com/10927428/43320776-f2053c6a-91a9-11e8-914a-832ac8b2c5e2.png)
This will create and/or delete elements of the database. Try not to do mistakes, even if there are solutions if something wrong happens.
This process can take time, especially if you are going to add a lot of new candidates.



I think that is enough for you to start experimenting with the tool.
Enjoy!
