### ISSUE TITLE
Loudness normalization of clips

### ISSUE THREAD

**Issue by lorenzo-romanelli** [MTG/freesound-datasets#139]
We should find a way to automatically adjust the volume of the clips according to some loudness measure.
This is needed in order to avoid destroying people's ears when very quiet sounds are followed by very loud sounds. Moreover, a consistent loudness shared among sounds _might_ yield to better UX and, thus, better annotations.

Right now, we implemented a simple client-side RMS normalization, but other proposed methods are:

- EBU R128
- ReplayGain

Essentia can already compute these descriptors, but we need to store the respective values on the db, and test the effectiveness of these methods (including RMS normalization) to see which one gives better results, avoiding clipping and/or other artifacts.

**Comment by xavierfav** [comment]
Fixed in #152.
