### ISSUE TITLE
sounds don't load in Safari 11.1

### ISSUE THREAD

**Issue by octothorpe8** [MTG/freesound-datasets#149]
Can't get the sounds to load at all in Safari. Adblock extensions disabled, and "allow website to automatically play media" is set to ON. 

<img width="1010" alt="macbook pro 2018-05-30 at 11 26 07 am" src="https://user-images.githubusercontent.com/15525768/40730287-4e09c50c-63fc-11e8-9e9e-f379e5c2550b.png">

**Comment by octothorpe8** [comment]
This is through a Mac. Just checked and am still unable to load sounds. Using Chrome is of course a solid workaround on MacOS.

**Comment by xavierfav** [comment]
Ok. We will try to replicate the bug and work on it!
Thank you for the effort.

**Comment by lorenzo-romanelli** [comment]
I cannot manage to replicate the issue on Safari 11.1, could you please verify if it is still present for you?
As @xavierfav mentioned, .ogg files are not well supported, but we use .mp3 if .ogg fails to load.

![screen shot 2018-07-04 at 11 26 38](https://user-images.githubusercontent.com/6919593/42269000-4388ce92-7f7d-11e8-8d3e-f870c5efa7b5.png)

**Comment by octothorpe8** [comment]
It's now working fine for me as well in Safari. I think Safari 11.1.1 came out in early June after I experienced that bug, so maybe something changed that fixed this. Anyway, thanks for the followup!
