### ISSUE TITLE
Download button unavailable - Early request of FSD dataset

### ISSUE THREAD

**Issue by jerpint** [MTG/freesound-datasets#157]
I'm currently logged in to the website, `https://datasets.freesound.org/fsd/discussion/` , I see the `Download` tab but it is not active (it doesn't link to anything). Is the dataset not yet available for download? Is it possible to request it temporarily?

**Comment by xavierfav** [comment]
The dataset is not available for download yet.
However, there is a resulting dataset with a fewer number of categories that is available to download [here](https://www.kaggle.com/c/freesound-audio-tagging/data).

It is possible to provide you the ground truth annotations generated in the Freesound Datasets platform, but you will have to download the corresponding audio content from Freesound (with the [API](https://freesound.org/docs/api/)).

Let us know if you are interested.

**Comment by jerpint** [comment]
@xavierfav I would be interested in getting the ground truth annotations you speak of, how would that work? Thank you!

**Comment by xavierfav** [comment]
We can share a Json file:
```python
{
  "<AudioSet_category_ID>": 
    {
      "PP": [<freesound_id>, ...],
      "PNP": [<freesound_id>, ...],
    }, 
  "<AudioSet_category_ID>":
    { ...
    ....
}
```

Where for each category you have a list of _Present and Predominant_ (PP) & _Present but Not Predominant_ (PNP) Freesound sound ids.
Categories come from the [AudioSet Ontology](https://github.com/audioset/ontology).

It is possible to include more stuff if you want, such as the candidate annotations generated by our automatic method, its quality estimate, the sounds that are considered _Not Present_, the raw votes, etc...
We use annotator agreement to consider that a sound category is present or not in an audio sample.
We use some tests in the forms to discard votes from _bad annotators_, or spam.
We also propagate the annotations from the leaf categories to some of its parents. 
Depending on your application, you can focus on very specific categories, broader ones, or all at once.

Then, for the audio content, you can get it from the Freesound API (as well as metadata and acoustic features).
For that, you can find the documentation [here](https://freesound.org/docs/api/), and some clients libraries for different languages [here](https://freesound.org/docs/api/client_libs.html).

Send me an email: xavier.favory[at]upf.edu

**Comment by zengqingfa** [comment]
Is there a way to download the bulk download of the relevant data?
![image](https://user-images.githubusercontent.com/39977054/56844058-e83e4680-68dc-11e9-8670-6bb3923b678a.png)
Like this one where I want to download all the audio of the car honking instead of one by one, what do I do?
