### ISSUE TITLE
Remove login with Github and Gmail

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#167]
- The Google+ API is being shut down.
- We have problem with the Github authentication #161.

Therefore, the simplest thing to do is to only allow authentication with Freesound.
We should add a message in the login page to tell people that some login with functionality have been removed. Maybe propose them to transfer their votes to their Freesound logged in user.

**Comment by alastair** [comment]
This will be useful to let us use the FS terms of service, too 👍
