### ISSUE TITLE
Login through annotator.freesound.org is not possible

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#173]
When trying to login from the new domain name (annotator.freesound.org), a AuthStateMissing exception is raised (e.g. check [this error](https://logserver.mtg.upf.edu/sentry/freesound-datasets/issues/1171/) in sentry).

The OAuth2 callback URL of the Freesound API credentials we use is redirecting to the old domain name (datasets.freesound.org), which causes this problem (the session is not shared across the different domain names).

To fix this, we could maybe:
- share the same cookie session with the two domains we use (probably a CrossDomainSessionMiddleware similar to what is proposed [here](https://stackoverflow.com/questions/2116860/django-session-cookie-domain-with-multiple-domains))
- have a redirection from datasets.freesound.org to annotator.freesound.org so that we do not serve the application to two domain names (we should also update the OAuth2 callback URL of the Freesound API credentials to point to the new domain)

**Comment by alastair** [comment]
The easiest way to fix this is to finalise the redirect. We shouldn't have to do anything with cookies.

**Comment by xavierfav** [comment]
Great. 
The credentials have been updated and will take effect on the next deploy.
Let's coordinate and finalist the redirect together with the deploy.
