### ISSUE TITLE
Can I download all the relevant audio at once?

### ISSUE THREAD

**Issue by zengqingfa** [MTG/freesound-datasets#177]
Like this one where I want to download all the audio of the car honking instead of one by one, what do I do?
![image](https://user-images.githubusercontent.com/39977054/56844105-8af6c500-68dd-11e9-860e-237526834be6.png)

**Comment by xavierfav** [comment]
We currently do not provide any way to download all the sounds at once.
This feature may be available in the future, but nor strict plan regarding it for now.
