### ISSUE TITLE
Remove duplicated votes

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#18]
After the Tagathon organized mid April, some duplicates were found in the DB:
Around 1000 votes of 45000 are duplicates. Closer inspection to the data showed that some vote pages were sent twice in when submitting (effect of double click in the "Submit" button maybe?). 

The timestamps are slightly different, so I guess we should identify duplicates looking at these fields (vote row of Vote):
- _vote.created_by_ 
- _vote.vote_
- _vote.annotation_id_
- _vote.created_at_ (are close)

It is quite easy using the Django ORM, however, backups should be done before launching the cleaning process, and a verification step after the cleaning should be done.

Cleaning process:
```
for row in Vote.objects.all():
    if Vote.objects.filter(created_by=row.created_by,
            annotation_id = row.annotation_id, 
            created_at__lte=row.created_at+timedelta(seconds=10),  
            created_at__gt=row.created_at-timedelta(seconds=10)).count() > 1:
        row.delete()
```

For the backup and verification I don't know what is the best way of doing it.

**Comment by ffont** [comment]
I'd say the cleaning process is something you simply do once.
Then we should update the code to prevent having duplicates.
This should be done probably both at the client level (i.e. disable submit button after clicking) and also at the server level (checking that there can only be one vote per user/annotation).

**Comment by xavierfav** [comment]
Pull request #21 submitted.
However, a unit test should be added for checking that submitting votes twice cannot happen.

**Comment by xavierfav** [comment]
@alastair could you please do the cleaning process on the FSD database?

**Comment by alastair** [comment]
:+1:

**Comment by alastair** [comment]
Done, with this code:
```py
from django.db.models import Count
from datasets import models
q = models.Vote.objects.values("created_by_id", "annotation_id").annotate(num_dup_annotations=Count('id')).filter(num_dup_annotations__gt=1)
for i in q:
    with transaction.atomic():
        votes = models.Vote.objects.filter(created_by_id=i["created_by_id"], annotation_id=i["annotation_id"]).order_by("created_at")
        for v in votes[1:]:
            v.delete()
```
