### ISSUE TITLE
Design of subsets for FSD 1st release

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#24]
The first release of FreesoundDataset (FSD) could have several _subsets_. For every subset, there will be a _balanced_ version (all sound classes have the same number of annotations), and an _unbalanced_ version. Appropriate _splits_ will be done for every version (tr/val/te or tr/te), including stratification for the unbalanced version. Also, user filtering or pack filtering could be considered, so that one user or pack is part of one set only. For now, 2 subsets are in mind: **Full** and **Medium**.

1. **Full**. The motivation is to keep as many categories as possible (ideally 632 of AudioSet ontology), so that the ontology is (almost) fully covered, avoiding data-driven “holes” that can be perpetuated in time. This will imply having a small number of agreed annotations in some of them. This is probably not enough for certain machine learning techniques, e.g., deep learning, but it can be enough for other approaches. Also, this is an intermediate step for the Medium subset.
* Features:  
  * _Balanced_ version includes a small number of annotations, e.g., 10 in each category
  * _Unbalanced_ version includes all available categories with all the annotations. Splits will require stratified sampling.

2.  **Medium**. The idea is to have a smaller number of categories that allow us to have a larger number of annotations in each of them. For instance, now we have selected 398 categories, where in each one of them we have at least 72 validated annotations, from which at least 30 or 40 are _Present_. The number of categories and annotations per category is to be decided.
* Features:  
  * _Balanced_  version includes a medium number of annotations, minimum of 50 or 60, in each category.
  * _Unbalanced_ version includes all the annotations for the selected categories. Splits will require stratified sampling.

**Comment by ffont** [comment]
This all sounds ok.
Can stratification and all of the constraints be computed automatically or there are things that should be done manually? Take this into account when you value what part of the dataset release should be automatically done by the platform. Another option is that when a dataset release is created, a csv file is upload with an index of splits, bla bla bla.

In fact the concept of splits is not yet part of the platform. Maybe this is a property that should be added in the `Annotations` model.

**Comment by edufonseca** [comment]
For simplicity, we could use **train/test splits** (instead of tr/val/te), also considering that for the _FSD1.0_medium_ we might not have a lot of data, especially in certain categories. It may be that doing 3 splits reduces the number of valid categories to be included.

Also, when it comes to the _balanced_ versions, we have to consider the existence of _multiple annotations_ per clip (currently, 2.62 in average). This turns very difficult to build a balanced set, strictly speaking.

Example: assume we want the _balanced_ train set for the _FSD1.0_medium_ to contain 60 (valid) examples per class. We start filling categories with 60 examples, but most of the audio clips have several annotations so they do +1 in several categories. So the set ends up not being balanced, _strictly speaking_.

In the case of AudioSet, they explain: "providing at least X examples for each of the Y sound classes that are used. Because of label co-occurrence, many classes have more examples.":
*  Balanced Train for Bark has 60 examples. So does the corresponding  Evaluation set.
*  Balanced Train for Dog has 273 examples.  Evaluation set has 230.
*  Balanced Train for Domestic animals, pets has 412 examples.  Evaluation set has 348.

**This all belongs to the _balanced_ version.** Something similar will happen to FSD.

It may be interesting to analyze the description of the balanced train set in AudioSet web:  "_22,176 segments from distinct videos chosen with the same criteria: providing at least 59 examples per class with the fewest number of total segments._"

Note:
1. 22k examples does not seem extremely large
2. 59 examples * 527 classes = 31k examples in total, ie, they have tried to minimize the number of total segments, taking into account the multiple annotations

Perhaps we should follow this approach for FSD.

**Comment by xavierfav** [comment]
Discussion related to FSD release are now done internally.
