### ISSUE TITLE
Subset of annotations for FSD 1st release

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#26]
After defining the mapping to create lists of candidate samples to fill the sound categories (#25), we should decide a subset of all mapped annotations where to concentrate the validations in the initial [validation task](https://datasets.freesound.org/fsd/contribute/validate_annotations/?help=1) for FSD 1st release. This is related to the design of the subsets #24, in such a way that the chosen subset of annotations should meet the requirements of the data subsets that we want to provide.

A simple example:
Suppose we want the _Medium_ subset of the FSD 1st release to have ~100k annotations with rater agreement. When validating an annotation, raters can say NP or U with certain probability. This means that we should select >100k annotations as starting point.

**Comment by edufonseca** [comment]
We could do this in two ways:

1. assuming a constant factor for all categories, eg, if we want to have 10 (_Present_) audio clips per category, we select 15 clips (annotations) to be validated
2. considering that the mapping may be better in certain categories, eg, for a well mapped category, 13 audio clips may be enough, while for a bad mapped one we could need 20

**Comment by xavierfav** [comment]
The prioritization of categories according to their number of ground truth annotation should bring us to a balanced dataset #38. 
We also choosed to omit the category that have two few annotation candidates.

I think there is nothing more to do for creating the subset

**Comment by xavierfav** [comment]
We decided not to create any subset, but rather prioritize some categories and annotations.
Some requirements are already functional (prioritize categories), and it will be improved in #133.
