### ISSUE TITLE
Improve guidelines for validation task

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#28]
Currently, the validation task available has a set of [instructions](https://datasets.freesound.org/fsd/contribute/validate_annotations/?help=1). When the improved annotation protocol is ready #27 , these guidelines should be updated, considering the crowdsourcing scenario. Providing a _short_ video instead of a text with instructions can be useful to transmit the message in a more appealing and dynamic way (although the corresponding text version could still be available).

The guidelines should focus on the **procedure** or protocol that the rater will follow, familiarizing him with the web tool, including at least:
* task description: question and response types
* training phase explanation
* validation phase explanation

**Comment by edufonseca** [comment]
It has been decided that:
1. eventually, the _guidelines video_ will mainly include screenshots and navigation through the _platform_, i.e., the video cannot be created until the platform is ready.
2. Because of 1., in the meantime, we will be having a short text instead. This text could be seen as the _script_ of the video. It will be updated and extended as the annotation protocol gets defined #27. For now, the main topics to cover are:

    1. Task Definition
  * Brief description
  * Question
  * Response types

    2. Task Procedure
  * Choosing category
  * Training phase: understanding category and its context
  * Validation Task

It was also decided that:
* **FAQ** will be accessed from the validation phase, similar as with the _HELP_ 
* **HELP** should only provide the most relevant info from the guidelines (similar to how it is now)
* both FAQ and HELP will be mentioned in the video

**Comment by edufonseca** [comment]
It was suggested that:
* both formats (text and video) could be available to the raters
* The guidelines should always be presented, and some mechanism should be implemented to _try_ to make sure the rater has read/watched them. Exceptions: if the user has recently carried out the task, eg, in the past _x_ days.

**Comment by xavierfav** [comment]
#85
#86
Instructions for Task1 have been made more compact.
Screenshot have been added instead of a video.
Tempo before skipping instruction page.
