### ISSUE TITLE
Split AudioSet ontology into groups for crowdsourcing validations

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#29]
Feedback gathered in conducted experiments shows that validating annotations of isolated categories may lead to inconsistent ratings, if the most similar categories are not considered. To address this issue, groups of related categories could be _(i)_ made and _(ii)_ suggested to the rater. The goal is to prevent raters from doing any random category by instead proposing small groups composed of siblings and small subfamilies. The groups should be small, taking into account possible lack of commitment in the crowdsourcing approach.

Assignment of these groups to raters may be at the beginning of the procedure, just after showing the guidelines #28, and before passing to the training phase #27, (that would be specific of the group of categories under consideration).

Assignment of these groups to raters may be done by:
* Suggesting groups to the rater, according to some criteria, e.g., categories with less validations.
* Letting the rater choose from a list according to his preference.

Hence this issue can be split into two tasks:
1. split the ontology into meaningful small groups of categories
2. design the criteria and a system that allows assigning groups to raters

**Comment by xavierfav** [comment]
I see different things we could do:

- organize the [table of categories ](https://datasets.freesound.org/fsd/contribute/validate_annotations/) by groups according to the hierarchy.

- ask raters to choose several categories to rate (and then start rating on them one by one). We could have a **user page** with some **pending tasks** that he chosed to do.

- recommend categories according to their previous ones. Again a **user page** might be interesting for this.

**Comment by ffont** [comment]
Would this user page be different for each dataset? and for each task in a dataset?
I'm just pointing out these things to trigger discussion. Let's also think about a simpler version of this. I like the idea of users choosing in which parts of a taxonomy they feel comfortable contributing more.

**Comment by jordipons** [comment]
These small groups are taxonomy/ontology and task dependent. Note that these are not dataset dependent, since we can have several datasets related to the same taxonomy/ontology. And also note that these groups are task dependent, however for most tasks these will be equal.

Therefore, in order to start, we can focus in a basic implementation where we assume using a single taxonomy/ontology where tasks are similar. I think this assumption is reasonable among the tasks we envision (#35 ).

**Comment by xavierfav** [comment]
We could add one step for "_Choose a group of category_" before _"Choose a category_".
When a user chooses a group, he is redirected to another page where he can choose for a specific category of the group.

This is making the user aware of the related categories, but it is not forcing him to stay in the group and validate only sounds from this group. He is free to go back to the "_Choose a group of category_" page and go for other groups.

Without any more "complicated" changes (e.g. adding a user page), I think we cannot really do better.

**Comment by edufonseca** [comment]
For now, it has been suggested to adopt a simpler strategy, based on assigning single categories (and not groups) to a rater. The motivation to create and propose groups of related categories was to gather consistent annotations across similar categories (typically siblings). But maybe we can get the rater to consider them without the need for groups generation, by **putting more emphasis in showing the context**. In this way, the user chooses one category and, in the training phase, the context (parent(s) and siblings) is shown.
 
Why so? It was discussed that creating groups has some issues:
* may be subject of criticism as it involves decisions with unclear criteria
* makes more sense with bigger groups that include most of the siblings. But this is too heavy for crowdsourcing. Smaller groups would not show much of the context.
* since groups would be small, there would be 100+ groups, ie, troublesome task to do
 
A possible procedure is as follows. After guidelines are over, a new page shows up with:
* an introductory _question_ at the top, eg, “Select a category:”
* 2 tabs:
    1. **Suggested** Categories (default)
        * Sorted according to predefined numeric score (create issue for this)
    2. **Of your choice**
        * Ask user to advance through the first 2 levels of ASO (3 if majority of siblings are also parents) based on his/her interest
        * Present categories sorted according to score (same as in _i_, but within the subset of categories after previous step)
 
At this point (by either way) we will have a list of sorted categories for the user to pick one. By selecting one, the user is redirected to a new page which is part of the training phase, when not only the selected category but also its siblings and parent(s) are listed in order to show the context.

**Comment by edufonseca** [comment]
Update on the procedure, @ffont :

After guidelines are over, a new page shows up, horizontally split in 2 parts:

* **Left side**: "What category would you like to validate?"
  * Ask user to advance through the first 2 levels of ASO (3 if majority of siblings are also parents) based on his/her interest
  * Present list with resulting subset of categories

* **Right side**: "Our priority list:"
  * Present list of categories that require validations the most

In both cases:
* the presented list is composed of categories are sorted according to predefined numeric score (#36)
* the first category is pre-selected but it is possible to choose a different one

By clicking _Continue_, the user navigates to a different page that shows the explicit part of the training phase.

**Comment by xavierfav** [comment]
This has been implemented in #40
