### ISSUE TITLE
Quality control

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#31]
As mentioned in #27 , ideally, the annotation protocol will consist of a training phase followed by a validation phase. Quality control mechanisms must be designed and implemented to ensure that gathered annotations are reliable. Among the possible approaches are:

* some [works](http://misrc.csom.umn.edu/workshops/2012/fall/Ipeirotis.pdf) focus on computing a quality score for each worker that contributed annotating. However, this may require to gather a significant amount of annotations.

* A more basic approach: every now and then we could present some annotations for which the response is i) evident and ii) known, to check worker’s response. It is possible that GoodSounds have implemented something in this line.

Further literature review may be required.

**Comment by xavierfav** [comment]
As said, for now only the second approach makes sense to implement.
However we need to clarify:

- do we want one (or two) known example per validation page? Or only in the first page of validation?
- which examples should we choose? 

If at each page the same known example is shown, the worker may notice something.
We could use the first pre-release examples? Are we sure they are all good?

**Comment by xavierfav** [comment]
The "basic approach" has been implemented in #44.
For now it is using only "positive examples".
We need more of this examples.

Please, start annotating! #30

**Comment by xavierfav** [comment]
#59
#68
#82

The approach implemented consist of adding 2 positive and 1 negative verification clips in a voting page for checking if a user is able to perform a validation task.

Each time a user start a new category and every 5 pages (after succeeding), verification clips are added.
