### ISSUE TITLE
Map of web

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#32]
Sketch platform's map of web and its rough content, as we want it to be for the crowdsourcing launch. A simple **_initial example_**:

* Initial welcome page:
    * Description of Freesound Datasets project
    * List of currently hosted datasets with a brief discription and _link_ to a page for each dataset
        * For every dataset:
          * Purpose & main characteristics
          * Available tasks to contribute
          * Releases available
            * For every release: functionalities supported (exploration, reporting, download, etc)

@xavierfav has already begun defining some of these concepts.

**Comment by edufonseca** [comment]
How about making it simpler? There is always time for improvement

Initial welcome page:
* Welcome to Freesound Datasets
* Brief description of Freesound Datasets project
* More info can be found in our ISMIR paper (link)
* List of currently hosted datasets. For every dataset:
  * **Name & Purpose** (very short) + a **link** to another page for each dataset (this will redirect to the current front page of FSD, where first thing to see is the Table with general stats + a brief description of the dataset)
  * **brief description/ main characteristics** (few lines)
* Credits: MTG UPF

**Comment by xavierfav** [comment]
The work has begun on branch iss32.

- Need a better text.
- Need link of publicly available ISMIR paper
- What about license?
