### ISSUE TITLE
Discussion/communication channels

### ISSUE THREAD

**Issue by edufonseca** [MTG/freesound-datasets#34]
Apart from hosting discussions through issues in this repository, we could consider other channels to promote communication:
1. We could have a mailing list, where people can ask things. This could also be used for announcements.
2. It was suggested to enable a contact form in the platform, and possibly have a blog where platform users can post.

any suggestions?

**Comment by jordipons** [comment]
IMO it would be nice to have (at least) these three channels:
1. GitHub - as now. It is a nice environment with appropriate tools for having general discussions.
2. Mailing list for announcements and community support (if the involved community wishes to communicate through there). This enables public contact with the project maintainers and the community.
3. Communication form though the website. This enables private direct contact with the project maintainers.

**Comment by ffont** [comment]
I agree with 1 and 2. However, 3 must be better defined because it could be very simple and very complex. What you probably want is a simple contact form which ends up sending an email to the admins and that's it.

For 2 you have to ask the creation of a mailing list via CAU. Will be something like freesound-datasets@llista.upf.edu.

**Comment by xavierfav** [comment]
- A [Google group](https://groups.google.com/forum/#!forum/freesound-datasets) has been created for allowing discussions.

- The GitHub will also be used for discussions.

- From the website, personal names are given (with way of constructing mail _name.surname@upf.edu_) from the [FAQ](https://datasets.freesound.org/faq/) page.

- The mtg@upf.edu email is also given in the [Discussion](https://datasets.freesound.org/discussion/) page
