### ISSUE TITLE
Add Category model

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#37]
For different reasons (to avoid using the json for holding information about categories and for storing attributes like _priority score_), adding a class `Category` to the models is needed.

First, I plan to:
- Add it to the models
- Add the attributes that correspond to the field in the _ontology.json_ file
- Add a `ManyToManyField` relation to `Category` in `Dataset` 
- Replace the value `CharField` of `Annotation` with a `ForeignKey` relation to `Category` 
- Add a process for loading and creating the instances of `Category` (from _ontology.json_ file) 
- Maybe replace some methods of `Taxonomy` that make more sense to have in `Category`

Later:
- Add _priority score_ attribute
- Add an async process for calculating the _priority score_

**Comment by ffont** [comment]
Very good,
I might consider naming it  TaxonomyNode, could help avoiding confusion and clarifying its relation to taxonomy. What do you think @alastair? How did you name these in acousticbrainz?

**Comment by xavierfav** [comment]
Ok,
Instead of a `ManyToManyField `relation to ` TaxonomyNode` in `Dataset`, wouldn't it be better to have it in `Taxonomy` ?

**Comment by ffont** [comment]
In my opinion, TaxonomyNode should have a ForeignKey relation with Taxonony and a OneToMany relation with other TaxonomyNode (parents).

El 13 juny 2017, a les 8:16, xavierfav <notifications@github.com> va escriure:

**Comment by ffont** [comment]
In my opinion, `TaxonomyNode` should have a `ForeignKey` relation with `Taxonony` and a `OneToMany` relation with other `TaxonomyNode` (parents).

**Comment by xavierfav** [comment]
TaxonomyNode model has been added #38
