### ISSUE TITLE
Get all Categories for a User is slow

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#41]
When a user goes to the page for selecting a category to annotate, the _priority table_ lists all the categories that the user can contribute to. 

Because a user can vote only once for an annotation, it is possible that there is no more annotation to validate for a specific category. 
For now, `Dataset.get_categories_to_validate(user)` get all the categories and then check the categories one by one to see if there are annotations left for the user to validate. This process is quite slow (takes 10 sec), and with several user using the platform, it could maybe be problematic (just supposition).

We could probably get all the categories with one query.

**Comment by xavierfav** [comment]
A better solution has been implemented
Now it is fast enough and does not query too much the database

**Comment by alastair** [comment]
It would be useful if you link to the commit that made this faster so that we can track where the change has been made (or reference the issue number in a commit - github will automatically link them)
