### ISSUE TITLE
code layout cleanup

### ISSUE THREAD

**Issue by alastair** [MTG/freesound-datasets#46]
A few things that might be easier to fix sooner rather than later about making sure we use a more "djangoish" layout for some parts of the application

* add `datasets/urls.py` for datasets specific urls, instead of having them in the main urls file
* Move templates specific to an application into that application - e.g. `datasets/templates/datasets/foo.html` instead of `templates/foo.html`

**Comment by xavierfav** [comment]
I am confused with the urls.
What is the way to split the urls in the several apps?
Simply  adding `datasets/urls.py` and moving some url pattern there does not work.
