### ISSUE TITLE
About page very slow to load

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#53]
We noticed that the about page (https://datasets.freesound.org/fsd/) is quite slow to load (~7 sec).

The ontology tree might cause this. Creating the nested dictionary that is then used by the tree.js library takes a while. 
I am considering adding an Ajax call to load this data asynchronously so that the page will be loaded more quickly.

**Comment by alastair** [comment]
Instead of just adding an ajax call you should first profile the page load to see where it is spending all of its time. It might be that you could add an index or change a query to increase the load speed without having to add complexity of javascript and another lookup.

**Comment by xavierfav** [comment]
The get_taxonomy_as_tree() function operates in a recursive way, doing a lot of small queries to the db (more than one thousand).
One way to overcome doing this queries each time someone goes to the default page of the platform would be to precompute it (store it in a json file or store it in Redis)
