### ISSUE TITLE
Sounds from Freesound are sometimes deleted

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#55]
It happens that sounds that have been selecting from the mapping, which creates the annotation candidates, are deleted.
Thus, the embeds presented in the validation forms are in this cases not working.

We should create a command for "synchronizing" our platform to Freesound.
We should check that the sounds are still in Freesound. And if they are not, flag them to indicate that for now we don't treat them.
We could still use them because the sound are actually not deleted from the Freesound database, but they are not publicly available.

This command could also get some metadata updated (eg. nb of downloads & ratings), that could be used for prioritizing some annotations #23.

**Comment by xavierfav** [comment]
This is very important for instance if verification examples are deleted, a user won't be able to successfully pass the test and therefore his votes won't count.

However, losing sounds is not very suitable, we should ensure that we keep Freesound content available even if a creator delete a sound. 
Maybe some changes have to be made on Freesound to give us access to deleted content @ffont.

**Comment by ffont** [comment]
Sounds are actually deleted from the Freesound database but we store a copy of the sounds and metadata for research purposes. As you mention, this copy not currently made available in API/embeds, we have to come up with an strategy for that problem which gives access to these sounds to Freesound datasets. For now the command option will be the fastest and more reliable one.

**Comment by xavierfav** [comment]
Yes, the command is needed anyway.

I have some doubts,
If I do 300k GET requests, for instance to an embed url of a sound ('http://freesound.org/embed/sound/iframe/<id>/simple/small/'), is it bad?

Instead, should I use the a text search request from the API (with filter on like 50 sound id), and check if in the results the ids are presents? (So it would be 6k requests)

**Comment by xavierfav** [comment]
Actually, I think this check should be done "online" instead of in a command: 
Each time we want to show sounds corresponding to annotations to vote, we should check if these sounds are still in Freesound. If not, we directly flag them and propose new ones.

This way, we avoid:
- to run a lot of requests at once
- a period in which some sounds are not available (this is very critical it the case of verification examples)

So I think I will do this check in the `contribute_validate_annotations_category` view function when the annotations to vote are selected, using a text search provided by the Freesound API.

**Comment by ffont** [comment]
You can try to do it online and do a search filtering by all the ids of the page (so with a single request you have enough). However this will mean that your page depends on Freesound responding on time which will make things slower. I think the best option is that you prepare your page so that it can still work if an embed is not loaded properly. Even if sounds have not been deleted there might be a puntual problem with the connection which makes one embed to fail. 

Then, I think you should go the command way using the API and run it maybe once a week or so. If your app can handle non loading embed you should be quite safe. Hopefully deleted sounds are not going to be a very common problem.

**Comment by xavierfav** [comment]
As agreed, we just provide the command solution.

A command as been added for updating the deleted state of sounds from Freesound.
For now, there is no scheduling for launching it periodically. 
The command has been launch once in the production server (on the 18/09/17). 
198 sounds appeared to be deleted on Freesound.

Annotations showed to users are now filtered to ensure that they do not correspond to deleted content.
