### ISSUE TITLE
AudioSet Ontology hierarchy not used

### ISSUE THREAD

**Issue by xavierfav** [MTG/freesound-datasets#93]
Currently we do not take into account the AudioSet Ontology hierarchy in our platform. This has different drawbacks:

- **Human effort is wasted** because it is needed to validate a category and its parents (when the mapping provides candidate annotations of categories from the same path for a given clip).
- The **prioritization of categories** according to their number of ground truth annotations does not count children counts (e.g. [Insect](https://datasets.freesound.org/fsd/explore/%252Fm%252F03vt0/) is prioritized even if its children -  `Cricket` `Fly, housefly` `Mosquito` `Bee, wasp, etc.` - have a lot of ground truth annotations).  
- The **prioritization of annotations** corresponding to clips having more ground truth annotations is not reliable for having more complete labeling (#90).

I propose to work on taking advantage of the hierarchy by:
- Populating the candidate annotations into their parents whenever possible ([this sheet](https://docs.google.com/spreadsheets/d/19i9FS3VM_w0IxpX6oCp8qC9eR3zov4jt3ryvLvdqkGI/edit#gid=0) already give some clues about it), and then:
    - At first, make available to validate only the leaf annotations of a same path for a given audio clip.
    - When a leaf annotation is considered as ground truth, populate its state (PP or PNP) to the path if possible.
    - If a disambiguation is needed (multiple _incompatible_ parents), allow to validate the different parents (if one is validated as ground truth, the other would be automatically considered as non ground truth). For instance with [Hiss](https://datasets.freesound.org/fsd/explore/%252Fm%252F07rjwbb/) and its _incompatible_ parents: [Cat](https://datasets.freesound.org/fsd/explore/%252Fm%252F01yrx/), [Snake](https://datasets.freesound.org/fsd/explore/%252Fm%252F078jl/), [Steam](https://datasets.freesound.org/fsd/explore/%252Fm%252F06wzb/)
    - If the leaf annotation is considered as NP or Unsure, maybe propose to validate its parent (e.g. the mapping could propose [Bark](https://datasets.freesound.org/fsd/explore/%252Fm%252F05tny_/) but it is a [Growling](https://datasets.freesound.org/fsd/explore/%252Fm%252F0ghcn6/) or a [Howl](https://datasets.freesound.org/fsd/explore/%252Fm%252F07qf0zm/) and then propose its Siblings) [This case needs to be a bit more discussed]

- Similar to what has been done in the [sheet](https://docs.google.com/spreadsheets/d/19i9FS3VM_w0IxpX6oCp8qC9eR3zov4jt3ryvLvdqkGI/edit#gid=0) about the multiple parents, incompatibility of Siblings might be worth to study in order to be able to discard some candidate annotations when there is a ground truth validation. For instance validate `Clapping` could automatically deactivate `Finger snapping` if PP?

**Comment by xavierfav** [comment]
After some discussion, we decided to:

- In order to not waste human effort on validating categories on the same hierarchy path for a given audio clip, reduce the number of candidate annotations by removing the annotations that have one candidate on one of its children path (keep only the _leaf_ candidates). For ambiguous categories having more than one parent, we would keep the candidate annotations whenever it is needed (see [this sheet](https://docs.google.com/spreadsheets/d/19i9FS3VM_w0IxpX6oCp8qC9eR3zov4jt3ryvLvdqkGI/edit#gid=155743763))

- In order to simplify the way we access the candidate and ground truth annotations, we plan to create two separated models: 
    - `CandidateAnnotation`: a table for the candidate annotations (linked to the user votes)
    - `VerifiedAnnotation`: a table for the annotations that have been verified. For the annotation that are considered as present, we (sometimes) populate the annotation by including the parents in the same path. The population rule is:
        - For categories that have only one parent, we create a _ground truth_ `VerifiedAnnotation` instance for each of the parent categories on the same hierarchy path.
        - For ambiguous cases, we follow the _rule of population_ stated in [this sheet](https://docs.google.com/spreadsheets/d/19i9FS3VM_w0IxpX6oCp8qC9eR3zov4jt3ryvLvdqkGI/edit#gid=155743763).

**Comment by xavierfav** [comment]
I am thinking of using an abstract model for defining all the fields and methods that would be common to `CandidateAnnotation` and `GroundTruthAnnotation`.
@ffont, is this a good idea?

**Comment by ffont** [comment]
No strong opinion on my side, if you've seen that having an abstract class is the way to go, then it sounds good. However, if the models are simple and with a certain potential of diverging over time, I'd rather define them separately.
